# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b760bbf492f09eeb1bb5da7c40bdcd688390e2e28ad57a38689928320e85da994671ea601e503e89c5ff070d95c3b681c4b1cf560ddcd5f624fa25ad19a830c1

test:
  secret_key_base: ae0b03cb7822a97ca0e87c241045db6df3f0d11dfb9ccab51c4c93bfa3bce7a3facecf450943db46f0f23adcdb899ddb418da8e6708025ce402b3504b98aa9a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
